function hsv2rgb(h,s,v){let f=(n,k=(n+h*6)%6)=>v-v*s*Math.max(Math.min(k,4-k,1),0);return [f(5),f(3),f(1)];}
export class Renderer{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext('webgl2')||canvas.getContext('webgl');if(!this.gl)throw Error('No WebGL');this.p=this.program(VS,FS);this.buf=this.gl.createBuffer();this.resize();addEventListener('resize',()=>this.resize());}
  sh(type,src){const gl=this.gl,s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
  program(vs,fs){const gl=this.gl,p=gl.createProgram();gl.attachShader(p,this.sh(gl.VERTEX_SHADER,vs));gl.attachShader(p,this.sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
  resize(){const d=Math.min(2,devicePixelRatio||1),w=this.canvas.clientWidth*d,h=this.canvas.clientHeight*d;if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}this.gl.viewport(0,0,w,h)}
  render(worlds, params, camera){const gl=this.gl,n=worlds.particleCount,dim=worlds.dim;this.resize();const data=new Float32Array(n*8);for(let i=0;i<n;i++){const off=i*dim;let x=0,y=0,z=0;for(let d=0;d<dim;d++){const q=worlds.q[off+d],a=d*1.618+camera.yaw;x+=q*Math.cos(a)*0.35;y+=q*Math.sin(a+camera.pitch)*0.35;z+=q*Math.cos(a*.7+camera.roll)*0.35}const u=worlds.u24[i];data[i*8]=x*params.zoom;data[i*8+1]=y*params.zoom;data[i*8+2]=z*params.zoom;data[i*8+3]=worlds.world[i]/Math.max(1,worlds.worldCount-1);data[i*8+4]=(u&255)/255;data[i*8+5]=((u>>8)&255)/255;data[i*8+6]=((u>>16)&255)/255;data[i*8+7]=Math.hypot(worlds.v[off],worlds.v[off+1]||0,worlds.v[off+2]||0)}
  gl.clearColor(.005,.006,.016,1);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.useProgram(this.p);gl.bindBuffer(gl.ARRAY_BUFFER,this.buf);gl.bufferData(gl.ARRAY_BUFFER,data,gl.DYNAMIC_DRAW);const stride=8*4;['aPos','aProp','aVel'].forEach((name,idx)=>{const loc=gl.getAttribLocation(this.p,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,idx===0?3:(idx===1?4:1),gl.FLOAT,false,stride,idx===0?0:(idx===1?3*4:7*4));});gl.uniform2f(gl.getUniformLocation(this.p,'uRes'),gl.canvas.width,gl.canvas.height);gl.uniform1f(gl.getUniformLocation(this.p,'uTime'),worlds.t);gl.uniform1f(gl.getUniformLocation(this.p,'uPoint'),params.pointSize);gl.uniform1f(gl.getUniformLocation(this.p,'uEntropy'),worlds.metrics.entropy||0);gl.drawArrays(gl.POINTS,0,n)}
}
const VS=`precision highp float;attribute vec3 aPos;attribute vec4 aProp;attribute float aVel;uniform float uPoint;varying vec4 vProp;varying float vVel;void main(){float z=aPos.z+5.;float p=1./max(.45,z);gl_Position=vec4(aPos.xy*p,aPos.z*.06,1.);gl_PointSize=uPoint*(1.+aVel*18.)*(.8+p*2.);vProp=aProp;vVel=aVel;}`;
const FS=`precision highp float;varying vec4 vProp;varying float vVel;uniform float uTime;uniform float uEntropy;vec3 hsv2rgb(vec3 c){vec3 p=abs(fract(c.xxx+vec3(0.,.666,.333))*6.-3.);return c.z*mix(vec3(1.),clamp(p-1.,0.,1.),c.y);}void main(){vec2 uv=gl_PointCoord*2.-1.;float r=dot(uv,uv);if(r>1.)discard;float core=exp(-r*3.8);float ring=exp(-pow(length(uv)-.62,2.)*42.);float h=fract(vProp.x*.5+vProp.y*.31+vProp.z*.17+uTime*.025);float sat=.55+vProp.w*.35;float val=.55+.18*uEntropy+.35*vVel;vec3 col=hsv2rgb(vec3(h,sat,val));gl_FragColor=vec4(col*(core+ring*.65),core+ring*.65);}`;
