'use client'
import {useEffect,useMemo,useState} from 'react'
import {Shield, Network, Activity, Cpu, Lock, Boxes} from 'lucide-react'
import HyperGraphCanvas from './ui/HyperGraphCanvas'
const API=process.env.NEXT_PUBLIC_GUARDIAN_API_URL || 'http://localhost:8450'
export default function Page(){
 const [events,setEvents]=useState<any[]>([]); const [risk,setRisk]=useState<any>({}); const [plan,setPlan]=useState<any>(null)
 useEffect(()=>{fetch(`${API}/risk/summary`).then(r=>r.json()).then(setRisk).catch(()=>{})},[])
 useEffect(()=>{fetch(`${API}/events/recent?limit=80`).then(r=>r.json()).then(setEvents).catch(()=>{})},[])
 useEffect(()=>{const ws=new WebSocket(API.replace('http','ws')+'/ws/events'); ws.onmessage=e=>{const m=JSON.parse(e.data); if(m.type==='event'){setEvents(v=>[m.event,...v].slice(0,160)); fetch(`${API}/risk/summary`).then(r=>r.json()).then(setRisk).catch(()=>{})}}; return()=>ws.close()},[])
 const nodes=useMemo(()=>events.slice(0,80).map((e,i)=>({id:i,label:e.source||'event',risk:e.risk||0,kind:e.kind})),[events])
 async function makePlan(formData:FormData){ const modules=String(formData.get('modules')||'monitoring,rag,llm-gateway').split(',').map(s=>s.trim()).filter(Boolean); const body={user:String(formData.get('user')||'kobalt'),name:String(formData.get('name')||'hypernode-lab'),modules,target:'exosys-rhiz',gpu:formData.get('gpu')==='on',network:'sinkhole0',dry_run:true}; const r=await fetch(`${API}/v1/hypergraph/plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); setPlan(await r.json()) }
 return <div className="shell"><aside className="side"><div className="brand">RHIZ SINKHOLE</div><p className="muted">Guardian cyber-observatory · exosys-rhiz · 10.45.3.0/24</p><div className="card"><Shield/> <b>Mode</b><p className="muted">Defensive sinkhole, dry-run gated orchestration, whitelisted hypernodes.</p></div><div className="card"><Lock/> <b>Gated Admin</b><p className="muted">Command allowlist, user whitelist, project lab controls, remote config plan-only.</p></div><div className="card"><Boxes/> <b>Modules</b><p><span className="pill">LXD</span><span className="pill">Docker</span><span className="pill">Ceph</span><span className="pill">RAG</span><span className="pill">LLM</span><span className="pill">VPN</span></p></div></aside><main className="main"><div className="hero"><HyperGraphCanvas nodes={nodes}/></div><div className="hud"><div className="card"><Activity/><div className="muted">Risk avg</div><div className={(risk.risk_avg||0)>.55?'metric warn':'metric ok'}>{((risk.risk_avg||0)*100).toFixed(1)}%</div></div><div className="card"><Shield/><div className="muted">Max risk</div><div className={(risk.risk_max||0)>.82?'metric crit':'metric'}>{((risk.risk_max||0)*100).toFixed(1)}%</div></div><div className="card"><Network/><div className="muted">Events</div><div className="metric">{risk.count||events.length}</div></div><div className="card"><Cpu/><div className="muted">Critical</div><div className="metric crit">{risk.critical_count||0}</div></div></div></main><aside className="right"><h2>Live events</h2><div className="events">{events.slice(0,16).map((e,i)=><div className="event" key={i}><b>{e.source}</b> <span className={e.severity==='critical'?'crit':e.severity==='warn'?'warn':'ok'}>{e.severity}</span><div className="muted">{e.kind} · risk {Math.round((e.risk||0)*100)}%</div><div>{e.message}</div></div>)}</div><h2>Hypernode Composer</h2><form className="composer" action={makePlan}><input name="user" defaultValue="kobalt"/><input name="name" defaultValue="hypernode-sinkhole-lab"/><textarea name="modules" defaultValue="monitoring,llm-gateway,rag,webgl-ui,dev-env,swarm,vpn"/><label><input type="checkbox" name="gpu" defaultChecked/> GPU container</label><button>Create dry-run plan</button></form>{plan&&<pre className="card">{JSON.stringify(plan,null,2)}</pre>}</aside></div>
}
