import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Atom,Waves,Radio,Network,ShieldCheck,Sparkles,SlidersHorizontal}from'lucide-react';
import{flowVector,projectHypersphere}from'./core/field.js';
import'./styles.css';
function Flowfield({params,frame}){const ref=useRef(null);useEffect(()=>{const c=ref.current,ctx=c.getContext('2d');let raf,t=0;const N=9000,pts=new Float32Array(N*4);for(let i=0;i<N;i++){const p=projectHypersphere(i,0,params,frame);pts[i*4]=p[0];pts[i*4+1]=p[1]}function rs(){c.width=c.clientWidth*devicePixelRatio;c.height=c.clientHeight*devicePixelRatio}rs();addEventListener('resize',rs);function loop(){t+=.016*params.time;const w=c.width,h=c.height;ctx.fillStyle='rgba(2,4,12,0.16)';ctx.fillRect(0,0,w,h);const e=frame?.metrics?.spectrum_entropy??.5;for(let i=0;i<N;i++){let x=pts[i*4],y=pts[i*4+1];const v=flowVector(x,y,t,params,frame);x+=v[0]*.003;y+=v[1]*.003;if(Math.hypot(x,y)>1.2||Math.random()<.0007){const p=projectHypersphere(i,t,params,frame);x=p[0];y=p[1]}pts[i*4]=x;pts[i*4+1]=y;ctx.fillStyle=`hsla(${(200+e*120+i*.03+t*12)%360},95%,${45+e*35}%,.42)`;ctx.fillRect(w*(.5+x*params.zoom),h*(.5+y*params.zoom),1.4*devicePixelRatio,1.4*devicePixelRatio)}ctx.globalCompositeOperation='lighter';for(const s of[-1,1]){const cx=w*(.5+s*.12*Math.cos(t*.2)),cy=h*(.5+s*.05*Math.sin(t*.31));const g=ctx.createRadialGradient(cx,cy,0,cx,cy,Math.min(w,h)*.18);g.addColorStop(0,`rgba(255,202,122,${.25+e*.25})`);g.addColorStop(.45,'rgba(114,221,255,.08)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(cx,cy,Math.min(w,h)*.18,0,Math.PI*2);ctx.fill()}ctx.globalCompositeOperation='source-over';ctx.strokeStyle='rgba(255,255,255,.35)';ctx.beginPath();ctx.arc(w/2,h/2,Math.min(w,h)*.155,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffca7a';ctx.font=`${18*devicePixelRatio}px ui-monospace`;ctx.textAlign='center';ctx.fillText('YEAR 0 · 0-POINT MARK',w/2,h*.08);raf=requestAnimationFrame(loop)}loop();return()=>{cancelAnimationFrame(raf);removeEventListener('resize',rs)}},[params,frame]);return <canvas className="flow" ref={ref}/>}
function Slider({label,value,min,max,step=.01,onChange}){return <label className="slider"><span>{label}</span><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(parseFloat(e.target.value))}/><b>{Number(value).toFixed(step>=1?0:2)}</b></label>}
function App(){const[params,setParams]=useState({gain:1,fold:8,mobius:5,swirl:.45,torus:1,hyper:.65,zoom:.86,time:1});const[frame,setFrame]=useState(null),[analysis,setAnalysis]=useState('');const patch=(k,v)=>setParams(p=>({...p,[k]:v}));async function load(){try{setFrame(await(await fetch('/api/field-frame')).json())}catch(e){}}async function analyze(){setAnalysis(JSON.stringify(await(await fetch('/agent/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({note:'Analyze flowfield paradigm block',frame})})).json(),null,2))}useEffect(()=>{load();const t=setInterval(load,1200);return()=>clearInterval(t)},[]);const m=frame?.metrics||{};return <main><section className="hero"><div><h1><Sparkles/> Entwine Paradigm FLOWFIELD</h1><p>Two-galaxy entropy singularity metaphor · hypergraph abstraction · SDR context · simulation only.</p></div><div className="safe"><ShieldCheck/> no physical force / no energy extraction</div></section><section className="layout"><div className="stage"><Flowfield params={params} frame={frame}/></div><aside className="panel"><div className="card"><h2><Atom/> Paradigm Block</h2><p><b>Year 0</b> as 0-point mark: symbolic origin where information/time distinction becomes observer-limited.</p><code>Π : D_discrete × Context → R_real_projection</code></div><div className="card"><h2><SlidersHorizontal/> Field Controls</h2>{[['gain',.1,3],['fold',1,20],['mobius',1,16],['swirl',0,2],['torus',0,2],['hyper',0,2],['zoom',.2,1.8]].map(x=><Slider key={x[0]} label={x[0]} value={params[x[0]]} min={x[1]} max={x[2]} onChange={v=>patch(x[0],v)}/>)}</div><div className="card"><h2><Radio/> SDR Context</h2><div className="kv"><span>source</span><b>{frame?.spectrum?.source||'none'}</b><span>entropy</span><b>{Number(m.spectrum_entropy||0).toFixed(3)}</b><span>power</span><b>{Number(m.power||0).toFixed(2)}</b><span>velocity</span><b>{Number(m.velocity_field_gain||0).toFixed(2)}</b><span>EM</span><b>{Number(m.em_field_gain||0).toFixed(2)}</b></div></div><div className="card"><h2><Network/> Hypergraph Paradigm</h2><ul><li>Grasshopper abstraction extraction</li><li>Self-supervised signal flow</li><li>Cascade orchestration</li><li>Mixed geometry z=[E,H,S]</li><li>Quasi-invariant drift monitor</li></ul></div><div className="card"><h2><Waves/> Agent Analysis</h2><button onClick={analyze}>Analyze frame</button><pre>{analysis}</pre></div></aside></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
